name: Linux build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Dependency install
      run: |
        sudo apt install ninja-build
        sudo apt install gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
    - name: Build & install
      env:
        CMAKE_OPTIONS: -DESSAUTIL_ENABLE_SFML=1
      run: ./install.sh
    - name: Run tests
      run: ./run-all-tests.sh
